name: Deploy stage
on:
  push:
    branches:
      - "homologacao"
jobs:
  deploy:
    name: Deploy homologacao
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: "/monitor/frontend/homologacao/"
          git-ftp-args: "--changed-only"

      - name: Build Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/group-apis/monitor/frontend/homologacao
            nvm ls
            yarn
            yarn build
