name: Deploy stage
on:
  push:
    branches:
      - "*"
      - "!master"
      - "!homologacao"
jobs:
  deploy:
    name: Deploy development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: "/var/group-apis/monitor/frontend/dev/"
          git-ftp-args: "--changed-only"
